server:
  port: 8080
  servlet:
    contextPath: /
  
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true
  
logging:
  level:
    root: INFO
    com.swayam.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

spring:
  kafka:
    bootstrap-servers: 192.168.1.4:9092    
