spring.kafka.streams.application-id: BankDetailApplication
spring.cloud.stream.bindings.output.contentType: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
  bindings.input.consumer.application-id: bank-details-aggregator
spring.cloud.stream.bindings.output:
  destination: bank-details-by-job
spring.cloud.stream.bindings.input:
  destination: bank-details
#spring.bindings.input.consumer.properties.spring.json.trusted.packages: '*'