server:
  port: 8090
  servlet:
    contextPath: /
  
logging:
  level:
    root: INFO
    com.swayam.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  flyway:
    locations: classpath:/sql
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:bank_details
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
