server:
  port: 8080
  servlet:
    contextPath: /
  
management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true
  
logging:
  level:
    root: INFO
    com.swayam.demo: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

spring:
  kafka:
    bootstrap-servers: 192.168.1.4:9092    
  flyway:
    locations: classpath:/sql
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://192.168.1.4:3306/camel_aggregation?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
