spring:
   data:
      cassandra:
         contact-points: localhost
         port: 9042
         ssl: false
         username: cassandra
         password: cassandra
         keyspace-name: reactive_demo
         
logging:
   level:
      com.datastax.driver: INFO  
      org.springframework.web: INFO       
